### ISSUE TITLE
Various security issues

### ISSUE THREAD

**Issue by EricTendian** [kkoves/limbo#4]
Hi there! I came across a couple security issues while browsing the code and wanted to point them out. If the site is ever going to be used in a production environment, might be a good idea to fix these.

Reflected XSS:
- https://github.com/kkoves/limbo/blob/master/lost.php#L45
- https://github.com/kkoves/limbo/blob/master/found.php#L45

SQL injection:
- https://github.com/kkoves/limbo/blob/master/includes/helpers.php#L36
- https://github.com/kkoves/limbo/blob/master/includes/helpers.php#L48
- https://github.com/kkoves/limbo/blob/master/includes/helpers.php#L119
- https://github.com/kkoves/limbo/blob/master/includes/helpers.php#L257

Plain-text passwords:
- https://github.com/kkoves/limbo/blob/master/limbo.sql#L21

Let me know if you have any questions.

**Comment by kkoves** [comment]
Thanks for the feedback. We were aware of the plaintext passwords issue, this will be addressed in the near future, as we just learned about encryption algorithms and functions in MySQL and PHP in class last week. We will be sure to address the other security flaws as well.

Thanks,
Krisztián
